name: Version

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install Dependencies
        run: yarn

      - name: Build packages
        run: yarn build

      - name: Build Typescript
        run: yarn ts:build

      - name: Create Release Pull Request
        uses: changesets/action@master
        with:
          version: yarn changeset:version
          publish: yarn release
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          NPM_TOKEN: '${{ secrets.NPM_TOKEN }}'

      - name: Publish website with package updates
        if: steps.changesets.outputs.published == 'true'
        run: yarn publish:sites
